// Code generated by ent, DO NOT EDIT.

package slackmessageattachment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/echo-stream/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldID, id))
}

// Color applies equality check predicate on the "Color" field. It's identical to ColorEQ.
func Color(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldColor, v))
}

// Fallback applies equality check predicate on the "Fallback" field. It's identical to FallbackEQ.
func Fallback(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldFallback, v))
}

// CallbackID applies equality check predicate on the "CallbackID" field. It's identical to CallbackIDEQ.
func CallbackID(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldCallbackID, v))
}

// AuthorID applies equality check predicate on the "AuthorID" field. It's identical to AuthorIDEQ.
func AuthorID(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorName applies equality check predicate on the "AuthorName" field. It's identical to AuthorNameEQ.
func AuthorName(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldAuthorName, v))
}

// AuthorSubname applies equality check predicate on the "AuthorSubname" field. It's identical to AuthorSubnameEQ.
func AuthorSubname(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldAuthorSubname, v))
}

// AuthorLink applies equality check predicate on the "AuthorLink" field. It's identical to AuthorLinkEQ.
func AuthorLink(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldAuthorLink, v))
}

// AuthorIcon applies equality check predicate on the "AuthorIcon" field. It's identical to AuthorIconEQ.
func AuthorIcon(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldAuthorIcon, v))
}

// Title applies equality check predicate on the "Title" field. It's identical to TitleEQ.
func Title(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldTitle, v))
}

// TitleLink applies equality check predicate on the "TitleLink" field. It's identical to TitleLinkEQ.
func TitleLink(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldTitleLink, v))
}

// Pretext applies equality check predicate on the "Pretext" field. It's identical to PretextEQ.
func Pretext(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldPretext, v))
}

// Text applies equality check predicate on the "Text" field. It's identical to TextEQ.
func Text(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldText, v))
}

// ImageURL applies equality check predicate on the "ImageURL" field. It's identical to ImageURLEQ.
func ImageURL(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldImageURL, v))
}

// ThumbURL applies equality check predicate on the "ThumbURL" field. It's identical to ThumbURLEQ.
func ThumbURL(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldThumbURL, v))
}

// ColorEQ applies the EQ predicate on the "Color" field.
func ColorEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "Color" field.
func ColorNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "Color" field.
func ColorIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "Color" field.
func ColorNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "Color" field.
func ColorGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "Color" field.
func ColorGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "Color" field.
func ColorLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "Color" field.
func ColorLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "Color" field.
func ColorContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "Color" field.
func ColorHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "Color" field.
func ColorHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldColor, v))
}

// ColorIsNil applies the IsNil predicate on the "Color" field.
func ColorIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldColor))
}

// ColorNotNil applies the NotNil predicate on the "Color" field.
func ColorNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldColor))
}

// ColorEqualFold applies the EqualFold predicate on the "Color" field.
func ColorEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "Color" field.
func ColorContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldColor, v))
}

// FallbackEQ applies the EQ predicate on the "Fallback" field.
func FallbackEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldFallback, v))
}

// FallbackNEQ applies the NEQ predicate on the "Fallback" field.
func FallbackNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldFallback, v))
}

// FallbackIn applies the In predicate on the "Fallback" field.
func FallbackIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldFallback, vs...))
}

// FallbackNotIn applies the NotIn predicate on the "Fallback" field.
func FallbackNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldFallback, vs...))
}

// FallbackGT applies the GT predicate on the "Fallback" field.
func FallbackGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldFallback, v))
}

// FallbackGTE applies the GTE predicate on the "Fallback" field.
func FallbackGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldFallback, v))
}

// FallbackLT applies the LT predicate on the "Fallback" field.
func FallbackLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldFallback, v))
}

// FallbackLTE applies the LTE predicate on the "Fallback" field.
func FallbackLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldFallback, v))
}

// FallbackContains applies the Contains predicate on the "Fallback" field.
func FallbackContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldFallback, v))
}

// FallbackHasPrefix applies the HasPrefix predicate on the "Fallback" field.
func FallbackHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldFallback, v))
}

// FallbackHasSuffix applies the HasSuffix predicate on the "Fallback" field.
func FallbackHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldFallback, v))
}

// FallbackIsNil applies the IsNil predicate on the "Fallback" field.
func FallbackIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldFallback))
}

// FallbackNotNil applies the NotNil predicate on the "Fallback" field.
func FallbackNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldFallback))
}

// FallbackEqualFold applies the EqualFold predicate on the "Fallback" field.
func FallbackEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldFallback, v))
}

// FallbackContainsFold applies the ContainsFold predicate on the "Fallback" field.
func FallbackContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldFallback, v))
}

// CallbackIDEQ applies the EQ predicate on the "CallbackID" field.
func CallbackIDEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldCallbackID, v))
}

// CallbackIDNEQ applies the NEQ predicate on the "CallbackID" field.
func CallbackIDNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldCallbackID, v))
}

// CallbackIDIn applies the In predicate on the "CallbackID" field.
func CallbackIDIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldCallbackID, vs...))
}

// CallbackIDNotIn applies the NotIn predicate on the "CallbackID" field.
func CallbackIDNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldCallbackID, vs...))
}

// CallbackIDGT applies the GT predicate on the "CallbackID" field.
func CallbackIDGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldCallbackID, v))
}

// CallbackIDGTE applies the GTE predicate on the "CallbackID" field.
func CallbackIDGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldCallbackID, v))
}

// CallbackIDLT applies the LT predicate on the "CallbackID" field.
func CallbackIDLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldCallbackID, v))
}

// CallbackIDLTE applies the LTE predicate on the "CallbackID" field.
func CallbackIDLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldCallbackID, v))
}

// CallbackIDContains applies the Contains predicate on the "CallbackID" field.
func CallbackIDContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldCallbackID, v))
}

// CallbackIDHasPrefix applies the HasPrefix predicate on the "CallbackID" field.
func CallbackIDHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldCallbackID, v))
}

// CallbackIDHasSuffix applies the HasSuffix predicate on the "CallbackID" field.
func CallbackIDHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldCallbackID, v))
}

// CallbackIDIsNil applies the IsNil predicate on the "CallbackID" field.
func CallbackIDIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldCallbackID))
}

// CallbackIDNotNil applies the NotNil predicate on the "CallbackID" field.
func CallbackIDNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldCallbackID))
}

// CallbackIDEqualFold applies the EqualFold predicate on the "CallbackID" field.
func CallbackIDEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldCallbackID, v))
}

// CallbackIDContainsFold applies the ContainsFold predicate on the "CallbackID" field.
func CallbackIDContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldCallbackID, v))
}

// AuthorIDEQ applies the EQ predicate on the "AuthorID" field.
func AuthorIDEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorIDNEQ applies the NEQ predicate on the "AuthorID" field.
func AuthorIDNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldAuthorID, v))
}

// AuthorIDIn applies the In predicate on the "AuthorID" field.
func AuthorIDIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldAuthorID, vs...))
}

// AuthorIDNotIn applies the NotIn predicate on the "AuthorID" field.
func AuthorIDNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldAuthorID, vs...))
}

// AuthorIDGT applies the GT predicate on the "AuthorID" field.
func AuthorIDGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldAuthorID, v))
}

// AuthorIDGTE applies the GTE predicate on the "AuthorID" field.
func AuthorIDGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldAuthorID, v))
}

// AuthorIDLT applies the LT predicate on the "AuthorID" field.
func AuthorIDLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldAuthorID, v))
}

// AuthorIDLTE applies the LTE predicate on the "AuthorID" field.
func AuthorIDLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldAuthorID, v))
}

// AuthorIDContains applies the Contains predicate on the "AuthorID" field.
func AuthorIDContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldAuthorID, v))
}

// AuthorIDHasPrefix applies the HasPrefix predicate on the "AuthorID" field.
func AuthorIDHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldAuthorID, v))
}

// AuthorIDHasSuffix applies the HasSuffix predicate on the "AuthorID" field.
func AuthorIDHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldAuthorID, v))
}

// AuthorIDIsNil applies the IsNil predicate on the "AuthorID" field.
func AuthorIDIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldAuthorID))
}

// AuthorIDNotNil applies the NotNil predicate on the "AuthorID" field.
func AuthorIDNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldAuthorID))
}

// AuthorIDEqualFold applies the EqualFold predicate on the "AuthorID" field.
func AuthorIDEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldAuthorID, v))
}

// AuthorIDContainsFold applies the ContainsFold predicate on the "AuthorID" field.
func AuthorIDContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldAuthorID, v))
}

// AuthorNameEQ applies the EQ predicate on the "AuthorName" field.
func AuthorNameEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldAuthorName, v))
}

// AuthorNameNEQ applies the NEQ predicate on the "AuthorName" field.
func AuthorNameNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldAuthorName, v))
}

// AuthorNameIn applies the In predicate on the "AuthorName" field.
func AuthorNameIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldAuthorName, vs...))
}

// AuthorNameNotIn applies the NotIn predicate on the "AuthorName" field.
func AuthorNameNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldAuthorName, vs...))
}

// AuthorNameGT applies the GT predicate on the "AuthorName" field.
func AuthorNameGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldAuthorName, v))
}

// AuthorNameGTE applies the GTE predicate on the "AuthorName" field.
func AuthorNameGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldAuthorName, v))
}

// AuthorNameLT applies the LT predicate on the "AuthorName" field.
func AuthorNameLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldAuthorName, v))
}

// AuthorNameLTE applies the LTE predicate on the "AuthorName" field.
func AuthorNameLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldAuthorName, v))
}

// AuthorNameContains applies the Contains predicate on the "AuthorName" field.
func AuthorNameContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldAuthorName, v))
}

// AuthorNameHasPrefix applies the HasPrefix predicate on the "AuthorName" field.
func AuthorNameHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldAuthorName, v))
}

// AuthorNameHasSuffix applies the HasSuffix predicate on the "AuthorName" field.
func AuthorNameHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldAuthorName, v))
}

// AuthorNameIsNil applies the IsNil predicate on the "AuthorName" field.
func AuthorNameIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldAuthorName))
}

// AuthorNameNotNil applies the NotNil predicate on the "AuthorName" field.
func AuthorNameNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldAuthorName))
}

// AuthorNameEqualFold applies the EqualFold predicate on the "AuthorName" field.
func AuthorNameEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldAuthorName, v))
}

// AuthorNameContainsFold applies the ContainsFold predicate on the "AuthorName" field.
func AuthorNameContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldAuthorName, v))
}

// AuthorSubnameEQ applies the EQ predicate on the "AuthorSubname" field.
func AuthorSubnameEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldAuthorSubname, v))
}

// AuthorSubnameNEQ applies the NEQ predicate on the "AuthorSubname" field.
func AuthorSubnameNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldAuthorSubname, v))
}

// AuthorSubnameIn applies the In predicate on the "AuthorSubname" field.
func AuthorSubnameIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldAuthorSubname, vs...))
}

// AuthorSubnameNotIn applies the NotIn predicate on the "AuthorSubname" field.
func AuthorSubnameNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldAuthorSubname, vs...))
}

// AuthorSubnameGT applies the GT predicate on the "AuthorSubname" field.
func AuthorSubnameGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldAuthorSubname, v))
}

// AuthorSubnameGTE applies the GTE predicate on the "AuthorSubname" field.
func AuthorSubnameGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldAuthorSubname, v))
}

// AuthorSubnameLT applies the LT predicate on the "AuthorSubname" field.
func AuthorSubnameLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldAuthorSubname, v))
}

// AuthorSubnameLTE applies the LTE predicate on the "AuthorSubname" field.
func AuthorSubnameLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldAuthorSubname, v))
}

// AuthorSubnameContains applies the Contains predicate on the "AuthorSubname" field.
func AuthorSubnameContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldAuthorSubname, v))
}

// AuthorSubnameHasPrefix applies the HasPrefix predicate on the "AuthorSubname" field.
func AuthorSubnameHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldAuthorSubname, v))
}

// AuthorSubnameHasSuffix applies the HasSuffix predicate on the "AuthorSubname" field.
func AuthorSubnameHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldAuthorSubname, v))
}

// AuthorSubnameIsNil applies the IsNil predicate on the "AuthorSubname" field.
func AuthorSubnameIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldAuthorSubname))
}

// AuthorSubnameNotNil applies the NotNil predicate on the "AuthorSubname" field.
func AuthorSubnameNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldAuthorSubname))
}

// AuthorSubnameEqualFold applies the EqualFold predicate on the "AuthorSubname" field.
func AuthorSubnameEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldAuthorSubname, v))
}

// AuthorSubnameContainsFold applies the ContainsFold predicate on the "AuthorSubname" field.
func AuthorSubnameContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldAuthorSubname, v))
}

// AuthorLinkEQ applies the EQ predicate on the "AuthorLink" field.
func AuthorLinkEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldAuthorLink, v))
}

// AuthorLinkNEQ applies the NEQ predicate on the "AuthorLink" field.
func AuthorLinkNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldAuthorLink, v))
}

// AuthorLinkIn applies the In predicate on the "AuthorLink" field.
func AuthorLinkIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldAuthorLink, vs...))
}

// AuthorLinkNotIn applies the NotIn predicate on the "AuthorLink" field.
func AuthorLinkNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldAuthorLink, vs...))
}

// AuthorLinkGT applies the GT predicate on the "AuthorLink" field.
func AuthorLinkGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldAuthorLink, v))
}

// AuthorLinkGTE applies the GTE predicate on the "AuthorLink" field.
func AuthorLinkGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldAuthorLink, v))
}

// AuthorLinkLT applies the LT predicate on the "AuthorLink" field.
func AuthorLinkLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldAuthorLink, v))
}

// AuthorLinkLTE applies the LTE predicate on the "AuthorLink" field.
func AuthorLinkLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldAuthorLink, v))
}

// AuthorLinkContains applies the Contains predicate on the "AuthorLink" field.
func AuthorLinkContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldAuthorLink, v))
}

// AuthorLinkHasPrefix applies the HasPrefix predicate on the "AuthorLink" field.
func AuthorLinkHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldAuthorLink, v))
}

// AuthorLinkHasSuffix applies the HasSuffix predicate on the "AuthorLink" field.
func AuthorLinkHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldAuthorLink, v))
}

// AuthorLinkIsNil applies the IsNil predicate on the "AuthorLink" field.
func AuthorLinkIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldAuthorLink))
}

// AuthorLinkNotNil applies the NotNil predicate on the "AuthorLink" field.
func AuthorLinkNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldAuthorLink))
}

// AuthorLinkEqualFold applies the EqualFold predicate on the "AuthorLink" field.
func AuthorLinkEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldAuthorLink, v))
}

// AuthorLinkContainsFold applies the ContainsFold predicate on the "AuthorLink" field.
func AuthorLinkContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldAuthorLink, v))
}

// AuthorIconEQ applies the EQ predicate on the "AuthorIcon" field.
func AuthorIconEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldAuthorIcon, v))
}

// AuthorIconNEQ applies the NEQ predicate on the "AuthorIcon" field.
func AuthorIconNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldAuthorIcon, v))
}

// AuthorIconIn applies the In predicate on the "AuthorIcon" field.
func AuthorIconIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldAuthorIcon, vs...))
}

// AuthorIconNotIn applies the NotIn predicate on the "AuthorIcon" field.
func AuthorIconNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldAuthorIcon, vs...))
}

// AuthorIconGT applies the GT predicate on the "AuthorIcon" field.
func AuthorIconGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldAuthorIcon, v))
}

// AuthorIconGTE applies the GTE predicate on the "AuthorIcon" field.
func AuthorIconGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldAuthorIcon, v))
}

// AuthorIconLT applies the LT predicate on the "AuthorIcon" field.
func AuthorIconLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldAuthorIcon, v))
}

// AuthorIconLTE applies the LTE predicate on the "AuthorIcon" field.
func AuthorIconLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldAuthorIcon, v))
}

// AuthorIconContains applies the Contains predicate on the "AuthorIcon" field.
func AuthorIconContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldAuthorIcon, v))
}

// AuthorIconHasPrefix applies the HasPrefix predicate on the "AuthorIcon" field.
func AuthorIconHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldAuthorIcon, v))
}

// AuthorIconHasSuffix applies the HasSuffix predicate on the "AuthorIcon" field.
func AuthorIconHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldAuthorIcon, v))
}

// AuthorIconIsNil applies the IsNil predicate on the "AuthorIcon" field.
func AuthorIconIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldAuthorIcon))
}

// AuthorIconNotNil applies the NotNil predicate on the "AuthorIcon" field.
func AuthorIconNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldAuthorIcon))
}

// AuthorIconEqualFold applies the EqualFold predicate on the "AuthorIcon" field.
func AuthorIconEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldAuthorIcon, v))
}

// AuthorIconContainsFold applies the ContainsFold predicate on the "AuthorIcon" field.
func AuthorIconContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldAuthorIcon, v))
}

// TitleEQ applies the EQ predicate on the "Title" field.
func TitleEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "Title" field.
func TitleNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "Title" field.
func TitleIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "Title" field.
func TitleNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "Title" field.
func TitleGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "Title" field.
func TitleGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "Title" field.
func TitleLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "Title" field.
func TitleLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "Title" field.
func TitleContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "Title" field.
func TitleHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "Title" field.
func TitleHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "Title" field.
func TitleIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "Title" field.
func TitleNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "Title" field.
func TitleEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "Title" field.
func TitleContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldTitle, v))
}

// TitleLinkEQ applies the EQ predicate on the "TitleLink" field.
func TitleLinkEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldTitleLink, v))
}

// TitleLinkNEQ applies the NEQ predicate on the "TitleLink" field.
func TitleLinkNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldTitleLink, v))
}

// TitleLinkIn applies the In predicate on the "TitleLink" field.
func TitleLinkIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldTitleLink, vs...))
}

// TitleLinkNotIn applies the NotIn predicate on the "TitleLink" field.
func TitleLinkNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldTitleLink, vs...))
}

// TitleLinkGT applies the GT predicate on the "TitleLink" field.
func TitleLinkGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldTitleLink, v))
}

// TitleLinkGTE applies the GTE predicate on the "TitleLink" field.
func TitleLinkGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldTitleLink, v))
}

// TitleLinkLT applies the LT predicate on the "TitleLink" field.
func TitleLinkLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldTitleLink, v))
}

// TitleLinkLTE applies the LTE predicate on the "TitleLink" field.
func TitleLinkLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldTitleLink, v))
}

// TitleLinkContains applies the Contains predicate on the "TitleLink" field.
func TitleLinkContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldTitleLink, v))
}

// TitleLinkHasPrefix applies the HasPrefix predicate on the "TitleLink" field.
func TitleLinkHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldTitleLink, v))
}

// TitleLinkHasSuffix applies the HasSuffix predicate on the "TitleLink" field.
func TitleLinkHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldTitleLink, v))
}

// TitleLinkIsNil applies the IsNil predicate on the "TitleLink" field.
func TitleLinkIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldTitleLink))
}

// TitleLinkNotNil applies the NotNil predicate on the "TitleLink" field.
func TitleLinkNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldTitleLink))
}

// TitleLinkEqualFold applies the EqualFold predicate on the "TitleLink" field.
func TitleLinkEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldTitleLink, v))
}

// TitleLinkContainsFold applies the ContainsFold predicate on the "TitleLink" field.
func TitleLinkContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldTitleLink, v))
}

// PretextEQ applies the EQ predicate on the "Pretext" field.
func PretextEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldPretext, v))
}

// PretextNEQ applies the NEQ predicate on the "Pretext" field.
func PretextNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldPretext, v))
}

// PretextIn applies the In predicate on the "Pretext" field.
func PretextIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldPretext, vs...))
}

// PretextNotIn applies the NotIn predicate on the "Pretext" field.
func PretextNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldPretext, vs...))
}

// PretextGT applies the GT predicate on the "Pretext" field.
func PretextGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldPretext, v))
}

// PretextGTE applies the GTE predicate on the "Pretext" field.
func PretextGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldPretext, v))
}

// PretextLT applies the LT predicate on the "Pretext" field.
func PretextLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldPretext, v))
}

// PretextLTE applies the LTE predicate on the "Pretext" field.
func PretextLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldPretext, v))
}

// PretextContains applies the Contains predicate on the "Pretext" field.
func PretextContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldPretext, v))
}

// PretextHasPrefix applies the HasPrefix predicate on the "Pretext" field.
func PretextHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldPretext, v))
}

// PretextHasSuffix applies the HasSuffix predicate on the "Pretext" field.
func PretextHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldPretext, v))
}

// PretextIsNil applies the IsNil predicate on the "Pretext" field.
func PretextIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldPretext))
}

// PretextNotNil applies the NotNil predicate on the "Pretext" field.
func PretextNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldPretext))
}

// PretextEqualFold applies the EqualFold predicate on the "Pretext" field.
func PretextEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldPretext, v))
}

// PretextContainsFold applies the ContainsFold predicate on the "Pretext" field.
func PretextContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldPretext, v))
}

// TextEQ applies the EQ predicate on the "Text" field.
func TextEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "Text" field.
func TextNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "Text" field.
func TextIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "Text" field.
func TextNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "Text" field.
func TextGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "Text" field.
func TextGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "Text" field.
func TextLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "Text" field.
func TextLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "Text" field.
func TextContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "Text" field.
func TextHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "Text" field.
func TextHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldText, v))
}

// TextIsNil applies the IsNil predicate on the "Text" field.
func TextIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldText))
}

// TextNotNil applies the NotNil predicate on the "Text" field.
func TextNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldText))
}

// TextEqualFold applies the EqualFold predicate on the "Text" field.
func TextEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "Text" field.
func TextContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldText, v))
}

// ImageURLEQ applies the EQ predicate on the "ImageURL" field.
func ImageURLEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldImageURL, v))
}

// ImageURLNEQ applies the NEQ predicate on the "ImageURL" field.
func ImageURLNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldImageURL, v))
}

// ImageURLIn applies the In predicate on the "ImageURL" field.
func ImageURLIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldImageURL, vs...))
}

// ImageURLNotIn applies the NotIn predicate on the "ImageURL" field.
func ImageURLNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldImageURL, vs...))
}

// ImageURLGT applies the GT predicate on the "ImageURL" field.
func ImageURLGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldImageURL, v))
}

// ImageURLGTE applies the GTE predicate on the "ImageURL" field.
func ImageURLGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldImageURL, v))
}

// ImageURLLT applies the LT predicate on the "ImageURL" field.
func ImageURLLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldImageURL, v))
}

// ImageURLLTE applies the LTE predicate on the "ImageURL" field.
func ImageURLLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldImageURL, v))
}

// ImageURLContains applies the Contains predicate on the "ImageURL" field.
func ImageURLContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldImageURL, v))
}

// ImageURLHasPrefix applies the HasPrefix predicate on the "ImageURL" field.
func ImageURLHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldImageURL, v))
}

// ImageURLHasSuffix applies the HasSuffix predicate on the "ImageURL" field.
func ImageURLHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldImageURL, v))
}

// ImageURLIsNil applies the IsNil predicate on the "ImageURL" field.
func ImageURLIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldImageURL))
}

// ImageURLNotNil applies the NotNil predicate on the "ImageURL" field.
func ImageURLNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldImageURL))
}

// ImageURLEqualFold applies the EqualFold predicate on the "ImageURL" field.
func ImageURLEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldImageURL, v))
}

// ImageURLContainsFold applies the ContainsFold predicate on the "ImageURL" field.
func ImageURLContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldImageURL, v))
}

// ThumbURLEQ applies the EQ predicate on the "ThumbURL" field.
func ThumbURLEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEQ(FieldThumbURL, v))
}

// ThumbURLNEQ applies the NEQ predicate on the "ThumbURL" field.
func ThumbURLNEQ(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNEQ(FieldThumbURL, v))
}

// ThumbURLIn applies the In predicate on the "ThumbURL" field.
func ThumbURLIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIn(FieldThumbURL, vs...))
}

// ThumbURLNotIn applies the NotIn predicate on the "ThumbURL" field.
func ThumbURLNotIn(vs ...string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotIn(FieldThumbURL, vs...))
}

// ThumbURLGT applies the GT predicate on the "ThumbURL" field.
func ThumbURLGT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGT(FieldThumbURL, v))
}

// ThumbURLGTE applies the GTE predicate on the "ThumbURL" field.
func ThumbURLGTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldGTE(FieldThumbURL, v))
}

// ThumbURLLT applies the LT predicate on the "ThumbURL" field.
func ThumbURLLT(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLT(FieldThumbURL, v))
}

// ThumbURLLTE applies the LTE predicate on the "ThumbURL" field.
func ThumbURLLTE(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldLTE(FieldThumbURL, v))
}

// ThumbURLContains applies the Contains predicate on the "ThumbURL" field.
func ThumbURLContains(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContains(FieldThumbURL, v))
}

// ThumbURLHasPrefix applies the HasPrefix predicate on the "ThumbURL" field.
func ThumbURLHasPrefix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasPrefix(FieldThumbURL, v))
}

// ThumbURLHasSuffix applies the HasSuffix predicate on the "ThumbURL" field.
func ThumbURLHasSuffix(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldHasSuffix(FieldThumbURL, v))
}

// ThumbURLIsNil applies the IsNil predicate on the "ThumbURL" field.
func ThumbURLIsNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldIsNull(FieldThumbURL))
}

// ThumbURLNotNil applies the NotNil predicate on the "ThumbURL" field.
func ThumbURLNotNil() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldNotNull(FieldThumbURL))
}

// ThumbURLEqualFold applies the EqualFold predicate on the "ThumbURL" field.
func ThumbURLEqualFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldEqualFold(FieldThumbURL, v))
}

// ThumbURLContainsFold applies the ContainsFold predicate on the "ThumbURL" field.
func ThumbURLContainsFold(v string) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.FieldContainsFold(FieldThumbURL, v))
}

// HasMessageID applies the HasEdge predicate on the "message_id" edge.
func HasMessageID() predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MessageIDTable, MessageIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageIDWith applies the HasEdge predicate on the "message_id" edge with a given conditions (other predicates).
func HasMessageIDWith(preds ...predicate.SlackMessage) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(func(s *sql.Selector) {
		step := newMessageIDStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SlackMessageAttachment) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SlackMessageAttachment) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SlackMessageAttachment) predicate.SlackMessageAttachment {
	return predicate.SlackMessageAttachment(sql.NotPredicates(p))
}
