// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/echo-stream/database/ent/predicate"
	"github.com/echo-stream/database/ent/slackmessage"
)

// SlackMessageDelete is the builder for deleting a SlackMessage entity.
type SlackMessageDelete struct {
	config
	hooks    []Hook
	mutation *SlackMessageMutation
}

// Where appends a list predicates to the SlackMessageDelete builder.
func (smd *SlackMessageDelete) Where(ps ...predicate.SlackMessage) *SlackMessageDelete {
	smd.mutation.Where(ps...)
	return smd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (smd *SlackMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, smd.sqlExec, smd.mutation, smd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (smd *SlackMessageDelete) ExecX(ctx context.Context) int {
	n, err := smd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (smd *SlackMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(slackmessage.Table, sqlgraph.NewFieldSpec(slackmessage.FieldID, field.TypeInt))
	if ps := smd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, smd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	smd.mutation.done = true
	return affected, err
}

// SlackMessageDeleteOne is the builder for deleting a single SlackMessage entity.
type SlackMessageDeleteOne struct {
	smd *SlackMessageDelete
}

// Where appends a list predicates to the SlackMessageDelete builder.
func (smdo *SlackMessageDeleteOne) Where(ps ...predicate.SlackMessage) *SlackMessageDeleteOne {
	smdo.smd.mutation.Where(ps...)
	return smdo
}

// Exec executes the deletion query.
func (smdo *SlackMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := smdo.smd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{slackmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (smdo *SlackMessageDeleteOne) ExecX(ctx context.Context) {
	if err := smdo.Exec(ctx); err != nil {
		panic(err)
	}
}
