// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/echo-stream/database/ent/predicate"
	"github.com/echo-stream/database/ent/slackmessageattachment"
)

// SlackMessageAttachmentDelete is the builder for deleting a SlackMessageAttachment entity.
type SlackMessageAttachmentDelete struct {
	config
	hooks    []Hook
	mutation *SlackMessageAttachmentMutation
}

// Where appends a list predicates to the SlackMessageAttachmentDelete builder.
func (smad *SlackMessageAttachmentDelete) Where(ps ...predicate.SlackMessageAttachment) *SlackMessageAttachmentDelete {
	smad.mutation.Where(ps...)
	return smad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (smad *SlackMessageAttachmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, smad.sqlExec, smad.mutation, smad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (smad *SlackMessageAttachmentDelete) ExecX(ctx context.Context) int {
	n, err := smad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (smad *SlackMessageAttachmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(slackmessageattachment.Table, sqlgraph.NewFieldSpec(slackmessageattachment.FieldID, field.TypeInt))
	if ps := smad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, smad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	smad.mutation.done = true
	return affected, err
}

// SlackMessageAttachmentDeleteOne is the builder for deleting a single SlackMessageAttachment entity.
type SlackMessageAttachmentDeleteOne struct {
	smad *SlackMessageAttachmentDelete
}

// Where appends a list predicates to the SlackMessageAttachmentDelete builder.
func (smado *SlackMessageAttachmentDeleteOne) Where(ps ...predicate.SlackMessageAttachment) *SlackMessageAttachmentDeleteOne {
	smado.smad.mutation.Where(ps...)
	return smado
}

// Exec executes the deletion query.
func (smado *SlackMessageAttachmentDeleteOne) Exec(ctx context.Context) error {
	n, err := smado.smad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{slackmessageattachment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (smado *SlackMessageAttachmentDeleteOne) ExecX(ctx context.Context) {
	if err := smado.Exec(ctx); err != nil {
		panic(err)
	}
}
