// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Application is the predicate function for application builders.
type Application func(*sql.Selector)

// SlackMessage is the predicate function for slackmessage builders.
type SlackMessage func(*sql.Selector)

// SlackMessageAttachment is the predicate function for slackmessageattachment builders.
type SlackMessageAttachment func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
